### ISSUE TITLE
it won't work on arm

### ISSUE THREAD

**Issue by l29ah** [wojtekka/6tunnel#2]
tho debian ships a patch to fix the problem, strange it's not there: http://dpaste.com/0VFFRV9

**Comment by l29ah** [comment]
oh, it's not the problem; wait

**Comment by l29ah** [comment]
https://bpaste.net/show/42ba680280ae tried to run it on arm

**Comment by l29ah** [comment]
Oh yeah, usage output contradicts the code, and https://dump.bitcheese.net/files/yxeraxa/10-6tunnel.c--option-f.patch is the patch for this. Also it's strange 6tunnel doesn't scream about bad options.

**Comment by wojtekka** [comment]
I applied this patch from Debian and release a new version. Let me know if the problem persists.

**Comment by wojtekka** [comment]
No reports whatsoever, so I'm closing this issue. If you feel that the problem persists, feel free to reopen it. For the record, the commit was 70fbe28a.
