### ISSUE TITLE
IPV4 option (-4) should warn if both addresses are already IPV4

### ISSUE THREAD

**Issue by jaalto** [wojtekka/6tunnel#4]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=610979

It would be great if you could help with this as you know the code best. Please let me know  if
this bug can be closed based on Roland's summary in message
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=610979#108

Thanks,
Jari

**Comment by jaalto** [comment]
Here is Roland's patch from the above bug report. Et me know if this can be dropped in case 0.11 already has tackled the issue.


[20-resolve-ipv4-address--bug601030.patch.txt](https://github.com/wojtekka/6tunnel/files/536036/20-resolve-ipv4-address--bug601030.patch.txt)

**Comment by wojtekka** [comment]
Added a warning in commit fc9e10f.
